apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001.azurecr.io/azvote/azure-vote-front
    newTag: 032dfb222fe528a10efe5fc0ba40c6b97dd8c67d
  - name: mtjacr001.azurecr.io/azvote/azure-vote-back
    newTag: 032dfb222fe528a10efe5fc0ba40c6b97dd8c67d
resources:
  - manifests.yaml