apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001.azurecr.io/azvote/azure-vote-front
    newTag: f5d6d864b8a84febbd8a151f7e95142f8a226c87
  - name: mtjacr001.azurecr.io/azvote/azure-vote-back
    newTag: f5d6d864b8a84febbd8a151f7e95142f8a226c87
resources:
  - manifests.yaml