apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: -vote-front
    newTag: 49bc95cc1a3e5e27f2ea683c3d2c92ce77c81a69
  - name: -vote-back
    newTag: 49bc95cc1a3e5e27f2ea683c3d2c92ce77c81a69
resources:
  - manifests.yaml