apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: mtjacr001.azurecr.io/azvote/azure-vote-front
    newTag: 352666646d26c8000aa0096d40c1c2f80a0d36f5
  - name: mtjacr001.azurecr.io/azvote/azure-vote-back
    newTag: 352666646d26c8000aa0096d40c1c2f80a0d36f5
resources:
  - manifests.yaml